# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4  # Tải mã nguồn từ GitHub về runner

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install dependencies and build project
      run: |
        cd frontend
        npm update autoprefixer
        npm ci
        CI=false npm run build --if-present
    - name: Install dependencies and build backend
      run: |
        npm ci
        CI=false npm run build --if-present

    - name: Deploy Frontend
      run: |
        echo ${{ secrets.SUDO_PASSWORD }} | sudo -S cp -r frontend/build/* /var/www/html/
    - name: Start/Restart Backend with PM2
      run: |
        echo ${{ secrets.SUDO_PASSWORD }} | sudo -S pm2 start server.js --name backend-app -- -p 5000 || echo "PM2 app already running, restarting..."
        echo ${{ secrets.SUDO_PASSWORD }} | sudo -S pm2 restart backend-app
